(in-package :data-ui)

(def-suite generator-suite
  :description "Generate-model hook tests")

(def-suite generator-pure-suite
  :description "Pure function tests (no model, no DB)"
  :in generator-suite)

(def-suite generator-integration-suite
  :description "Integration tests (need modelbank-test + DB)"
  :in generator-suite)

;;; Reusable valid model text for integration tests.
(defparameter *gen-valid-model*
  (concatenate 'string
    "'(:title \"Gen\" :name \"gen\" :version \"0.1\""
    "  :types (:todos (:table t"
    "    :create :auto :update :auto :delete :auto :display t"
    "    :fields (:name (:type :text :identity t"
    "      :ui (:label \"Name\" :widget :textbox)"
    "      :source (:view :main :column :name :agg :first)"
    "      :column t :not-null t :unique t))"
    "    :list-form (:fields t)"
    "    :update-form (:fields t)"
    "    :add-form (:fields t))))"))

;;; ---------------------------------------------------------------------------
;;; Pure function tests (no model, no DB)
;;; ---------------------------------------------------------------------------

(in-suite generator-pure-suite)

(test strip-leading-comments-basic
  "strip-leading-lisp-comments removes ;; and blank lines."
  (is (equal "'(:types (:foo))"
        (u:trim
          (strip-leading-lisp-comments
            ";; Purpose: test
'(:types (:foo))"))))
  (is (equal "'(:types (:foo))"
        (u:trim
          (strip-leading-lisp-comments
            ";; line 1
;; line 2

'(:types (:foo))"))))
  (is (equal ""
        (strip-leading-lisp-comments
          ";; only comments
;; more comments"))))

(test strip-leading-comments-preserves-inner
  "Comments inside the plist body are preserved."
  (let ((result (strip-leading-lisp-comments
                  "'(:types ;; inner comment
     (:foo))")))
    (is (search ";; inner comment" result))
    (is (search "'(:types" result))))

(test validate-deploy-model-text-accepts-comments
  "validate-deploy-model-text accepts leading ;; headers."
  (let ((result (validate-deploy-model-text
                  (concatenate 'string
                    ";; Purpose: test
;; Author: rose
" *gen-valid-model*))))
    (is (getf result :ok) "Should succeed with leading comments")
    (is-false (getf result :error))))

(test validate-deploy-model-text-rejects-bad-body
  "validate-deploy-model-text still rejects garbage after comments."
  (let ((result (validate-deploy-model-text
                  ";; comment
garbage")))
    (is (getf result :error))))

(test validate-deploy-model-text-parse-error
  "Parse errors stay one-line messages (the model text is not
embedded — it lives in the :model field via the failed-attempt
write).  Both parse sites: unreadable text and a readable form
whose body is not a plist."
  (let ((result (validate-deploy-model-text "'(:types (:foo")))
    (is (equal "parse error in model text" (getf result :error))))
  (let ((result (validate-deploy-model-text "'not-a-plist")))
    (is (equal "parse error in model text" (getf result :error)))))

(test first-line
  "first-line returns text up to the first newline."
  (is (equal "abc" (first-line "abc
def")))
  (is (equal "abc" (first-line "abc"))))

(test failed-model-p
  "failed-model-p: empty/blank/nil or a ;; failed: first line.
A working model's header never matches."
  (is (failed-model-p nil))
  (is (failed-model-p ""))
  (is (failed-model-p "   "))
  (is (failed-model-p
        ";; failed: parse error in model text
'(:types (:foo"))
  (is-false (failed-model-p
              ";; Generated by Data UI Model Generator
'(:types (:foo))"))
  (is-false (failed-model-p "'(:types (:foo))")))

(test generate-model-error-line-one-line
  "The ;; failed: marker line collapses newlines so it stays one
line — the prefix check on the next Generate depends on that."
  (is (equal "line1 line2"
        (generate-model-error-line "line1
line2")))
  (is (equal "no newlines"
        (generate-model-error-line "no newlines"))))

(test clean-llm-response-strips-fences
  "clean-llm-response strips markdown fences."
  (is (equal "'(:types (:foo))"
        (clean-llm-response
          "```lisp
'(:types (:foo))
```")))
  (is (equal "'(:types (:foo))"
        (clean-llm-response
          "```
'(:types (:foo))
```")))
  (is (equal "'(:types (:foo))"
        (clean-llm-response "'(:types (:foo))")))
  (is (equal "'(:types (:foo))"
        (clean-llm-response
          "Here is the model:
```common-lisp
'(:types (:foo))
```
Hope this helps!"))))

(test generate-model-header-format
  "generate-model-header produces ;; comment lines."
  (let ((header (generate-model-header "a todo app")))
    (is (search ";; Generated by Data UI Model Generator" header))
    (is (search ";; Created:" header))
    (is (search ";; Prompt: a todo app" header))))

(test generate-model-header-truncates-long-prompts
  "generate-model-header truncates prompts over 60 chars."
  (let ((header (generate-model-header
                  (make-string 100 :initial-element #\x))))
    (is (search "..." header))))

(test generate-model-example-files-pinned-set
  "generate-model-example-files returns exactly the pinned demo set —
a new demo lands only by updating this pin, forcing a conscious
token-budget re-check instead of silently inflating every prompt.
(shopping.lisp joined the set 2026-09-27: an LLM-generated demo,
kept as a living example of generator output.)"
  (is (equal
        '("books" "chores" "file-server" "gift-tracker" "modelbank"
           "parts" "recurring" "shopping" "todos" "widgets")
        (mapcar (lambda (path)
                  (u:replace-extension (u:filename-only path) ""))
          (generate-model-example-files)))))

(test generate-model-example-block-skips-unreadable
  "generate-model-example-block returns nil for unreadable files —
one stray file never fails a generation."
  (is-false (generate-model-example-block "/no/such/file.lisp")))

(test generate-model-user-message-includes-prior-model
  "generate-model-user-message includes the prior model, framed as
advisory, with the description last (the final signal)."
  (let ((message (generate-model-user-message "A todo app"
                    "'(:name \"prior\")")))
    (is (search "previous version of this model" message))
    (is (search "'(:name \"prior\")" message))
    (is (search "A todo app" message))
    (is (> (search "'(:name \"prior\")" message)
           (search "previous version of this model" message)))
    (is (> (search "A todo app" message)
           (search "'(:name \"prior\")" message)))))

(test generate-model-user-message-omits-blank-prior-model
  "A blank or nil prior model omits the block entirely — erase =
fresh start."
  (dolist (prior (list nil "" "   "))
    (let ((message (generate-model-user-message "A todo app" prior)))
      (is-false (search "previous version of this model" message)
        "blank prior ~s must omit the block" prior)
      (is (search "A todo app" message)))))

(test sanitize-name-component
  "sanitize-name-component: downcase, non-[a-z0-9-] → dash, edges
trimmed — record :name is author/LLM data, never path data."
  (is (equal "model-bank-demo"
        (sanitize-name-component "Model Bank Demo!!")))
  (is (equal "a-b-c" (sanitize-name-component "  A/B C ")))
  (is (equal "" (sanitize-name-component "%%%")))
  (is (equal "" (sanitize-name-component nil))))

(test generate-model-prompt-log-filename-shape
  "Filename is <app>-<record>-<compact-ts>.org, both name
components sanitized."
  (let ((name (generate-model-prompt-log-filename
                "Model Bank" "Shop Ping!")))
    (is (re:scan "^model-bank-shop-ping-\\d{8}T\\d{6}\\.org$"
          name)
        "got ~a" name)))

(test org-escape-src-lines
  "Lines starting with *, #+, or , get a comma prefix inside src
blocks — org strips one leading comma on export / C-c ' edit, so
markdown bold (**) and keyword-looking lines stay literal."
  (let ((out (org-escape-src-lines "**Filter operators**
#+begin_example
,already-escaped
plain line")))
    (is (search ",**Filter operators**" out))
    (is (search ",#+begin_example" out))
    (is (search ",,already-escaped" out))
    (is (re:scan "(?m)^plain line$" out)
        "plain lines must not gain a comma prefix")))

(defun th-gen-temp-dir ()
  "Fresh temp directory under /tmp (namestring, trailing slash)
for prompt-log tests — never the default /data dir.  Caller
deletes it via th-gen-delete-dir."
  (namestring
    (ensure-directories-exist
      (format nil "/tmp/gen-prompt-log-test-~a/"
        (re:regex-replace-all "[^a-zA-Z0-9-]"
          (format nil "~a" (u:uuid)) "-")))))

(defun th-gen-delete-dir (dir)
  "Best-effort recursive delete of a th-gen-temp-dir directory."
  (ignore-errors
    (uiop:delete-directory-tree
      (pathname (string-right-trim "/" dir))
      :validate t :if-does-not-exist :ignore)))

(test generate-model-log-prompt-writes-file
  "generate-model-log-prompt writes one org-mode file into a temp
dir (not /data): level-1 headings for the former JSON keys, the
system prompt structured as two level-2 children (Model Syntax
Reference markdown block, Examples prose + lisp block).  The
prose / example blocks are regenerated inside the logger, so real
demo content rides the file even under a synthetic parts plist."
  (let* ((dir (th-gen-temp-dir))
         (*generate-model-prompt-log-dir* dir)
         (path (generate-model-log-prompt
                 '(:url "http://fake" :model "test-model"
                   :api-key "fake-key" :temperature 0.3 :max-tokens 16)
                 "shopping"
                 '(:reference "SYSTEM PROMPT TEXT"
                   :examples "whatever rides the JSON body")
                 "USER MESSAGE TEXT")))
    (unwind-protect
      (progn
        (is-true path "Should return the written path")
        (is-true (uiop:file-exists-p path) "File should exist")
        (let ((content (u:slurp path)))
          ;; Level-1 headings, one per former JSON key
          (dolist (heading '("* timestamp" "* model" "* temperature"
                             "* record-name" "* system-prompt"
                             "* user-message"))
            (is (search heading content)
              "missing heading ~a" heading))
          ;; Level-2 children under * system-prompt
          (is (search "** Model Syntax Reference" content)
            "missing level-2 reference heading")
          (is (search "** Examples" content)
            "missing level-2 examples heading")
          (is (re:scan "(?m)^shopping$" content)
            "record-name value under its heading")
          (is (re:scan "(?m)^test-model$" content)
            "model value under its heading")
          ;; Reference rides a markdown src block; demos ride one
          ;; lisp block; user message rides plain text
          (is (search "#+begin_src markdown" content))
          (is (search "#+end_src" content))
          (is (re:scan "(?m)^#\\+begin_src lisp$" content)
            "examples must ride one lisp src block")
          (is (search "SYSTEM PROMPT TEXT" content))
          (is (search "USER MESSAGE TEXT" content))
          ;; The regenerated example blocks are real demos
          (is (search ";; --- " content)
            "example-model banner must ride the lisp block")
          (is (search "models/todos.lisp" content))
          (is-false (search "fake-key" content)
            "the key never rides the body (header-only secret)")))
      (th-gen-delete-dir dir))))

(test generate-model-log-prompt-best-effort
  "A logging failure never signals: an impossible path (under a
file) returns NIL, Generate stays alive."
  (let* ((tmp (format nil "/tmp/gen-prompt-log-blocker-~a" (u:uuid)))
         (*generate-model-prompt-log-dir*
           (concatenate 'string tmp "/not-a-dir/")))
    (unwind-protect
      (progn
        (u:spew "blocker" tmp)
        (is-false (generate-model-log-prompt
                    '(:model "m" :temperature 0.3)
                    "shopping" '(:reference "sys" :examples "sys")
                    "user")
          "Failed write must return NIL")
        (finishes
          (generate-model-log-prompt
            '(:model "m" :temperature 0.3)
            "shopping" '(:reference "sys" :examples "sys")
            "user")))
      (ignore-errors (uiop:delete-file-if-exists tmp)))))

;;; ---------------------------------------------------------------------------
;;; Integration tests (need modelbank-test + DB)
;;; ---------------------------------------------------------------------------

(in-suite generator-integration-suite)

(defun th-gen-seed-llm-config ()
  "Insert the llm-config secret as admin, or re-insert if it was
deleted.  Idempotent: deletes any existing llm-config rows first
to avoid duplicates.  Returns NIL."
  (th-gen-delete-llm-config)
  (be-insert :secrets
    (list :name "llm-config"
          :value ":url \"http://fake\" :model \"fake\" :api-key \"fake-key\""
          :description "Test LLM config")
    "admin")
  nil)

(defun th-gen-delete-llm-config ()
  "Delete all llm-config secrets so read-llm-config-missing can run."
  (let* ((result (be-list :secrets "admin" :form :update-form))
         (records (getf result :records)))
    (dolist (record records)
      (when (equal (getf record :name) "llm-config")
        (let ((id (getf record :id)))
          (when id
            (handler-case (be-delete :secrets id "admin")
              (error ())))))))
  nil)

(defun th-gen-make-user (&optional (name "gen-user"))
  "Create a user with ai-user and models-user roles.
Idempotent: skips creation if the user already exists."
  (unless (a:get-id *rbac* "users" name)
    (th-make-user name :roles '("ai-user" "models-user")))
  name)

(defparameter *gen-row-counter* 0)

(defun th-gen-make-model-row (user description)
  "Insert a :models row with a unique name, empty model.
Returns the new record ID."
  (incf *gen-row-counter*)
  (be-insert :models
    (list :name (format nil "gen-test-~d" *gen-row-counter*)
          :description description
          :model "")
    user
    :roles '("models-user")))

(defun th-gen-record (id user)
  "Fetch a :models record by ID."
  (getf (rec id user :type-key :models) :record))

(defun th-gen-status (id user)
  "Fetch the generate-status field for a :models record."
  (getf (th-gen-record id user) :generate-status))

(defun th-gen-wait (id user &optional (timeout 50))
  "Poll until generate-status is no longer running. Returns status."
  (loop for i below timeout
        for status = (th-gen-status id user)
        when (and status (not (equal status "running")))
          do (return status)
        do (sleep 0.1)
        finally (return (th-gen-status id user))))

(test generate-hook-override-writes-no-prompt-log
  "The LLM-override path (tests) short-circuits before the prompt
log — a Generate click under the override leaves the log dir
untouched.  Integration-suite (needs the modelbank-test model,
which run-generator-tests compiles after the pure suite)."
  (th-gen-seed-llm-config)
  (th-gen-make-user "gen-admin")
  (let ((id (th-gen-make-model-row "gen-admin" "A todo app")))
    (is-true id)
    (let ((dir (th-gen-temp-dir)))
      (unwind-protect
        (let* ((*generate-model-prompt-log-dir* dir)
               (*generate-model-llm-override*
                 (lambda (desc prior)
                   (declare (ignore desc prior))
                   (list :ok *gen-valid-model*))))
          (be-action :models id :generate "gen-admin")
          (th-gen-wait id "gen-admin")
          (is (null (uiop:directory-files (pathname dir)))
              "override runs must write no prompt-log files"))
        (progn
          (th-gen-delete-dir dir)
          (be-delete :models id "gen-admin"))))))

(test read-llm-config-missing
  "read-llm-config returns error when secret is absent."
  (th-gen-delete-llm-config)
  (let ((result (read-llm-config)))
    (is (getf result :error))))

(test read-llm-config-success
  "read-llm-config parses a valid llm-config secret."
  (th-gen-seed-llm-config)
  (let ((result (read-llm-config)))
    (is (getf result :ok) "Should parse successfully")
    (is (equal "http://fake"
           (getf (getf result :ok) :url)))))

(test admin-secret-value-returns-value
  "admin-secret-value returns the :value for a named secret."
  (th-gen-seed-llm-config)
  (let ((val (admin-secret-value "llm-config")))
    (is (search "fake-key" (or val "")))))

(test apply-generated-model-text-writes-valid
  "apply-generated-model-text writes a valid model with header."
  (th-gen-make-user "gen-admin")
  (let ((id (th-gen-make-model-row "gen-admin" "A todo app")))
    (is-true id)
    (unwind-protect
      (let* ((record (th-gen-record id "gen-admin"))
             (result (apply-generated-model-text
                       :models record "gen-admin" :model
                       "A todo app" *gen-valid-model* "")))
        (is (getf result :ok) "Apply should succeed")
        (let ((model-val (getf (th-gen-record id "gen-admin") :model)))
          (is (search ";; Generated by" (or model-val "")))
          (is (search ":types" (or model-val "")))))
      (be-delete :models id "gen-admin"))))

(test apply-generated-model-text-rejects-invalid
  "apply-generated-model-text rejects invalid model text.  With an
empty prior model the failed attempt IS written, prefixed by the
one-line ;; failed: marker (error next to the artifact)."
  (th-gen-make-user "gen-admin")
  (let ((id (th-gen-make-model-row "gen-admin" "A todo app")))
    (is-true id)
    (unwind-protect
      (let* ((record (th-gen-record id "gen-admin"))
             (result (apply-generated-model-text
                       :models record "gen-admin" :model
                       "A todo app" "'garbage" "")))
        (is (getf result :error) "Should reject invalid model")
        (let ((model-val (getf (th-gen-record id "gen-admin") :model)))
          (is (search ";; failed: " (or model-val ""))
              "Failed attempt should be written with marker")
          ;; Marker is the FIRST line and stays one line
          (is (u:starts-with (first-line (or model-val ""))
                ";; failed: "))
          ;; Provenance header follows, then the failed body
          (is (search ";; Generated by" (or model-val "")))
          (is (search "garbage" (or model-val "")))))
      (be-delete :models id "gen-admin"))))

(test apply-generated-model-text-preserves-working-model
  "Rule 2.2: a prior WORKING model is never clobbered by a failed
attempt — the field keeps the working model untouched."
  (th-gen-make-user "gen-admin")
  (let ((id (th-gen-make-model-row "gen-admin" "A todo app")))
    (is-true id)
    (unwind-protect
      (progn
        ;; Seed the working model (the resolved field value in the
        ;; real flow; prior-model is what the field holds)
        (be-set-field-value :models id :model *gen-valid-model*
          "gen-admin")
        (let* ((record (th-gen-record id "gen-admin"))
               (working (getf record :model))
               (result (apply-generated-model-text
                         :models record "gen-admin" :model
                         "A todo app" "'garbage" working)))
          (is (getf result :error) "Should reject invalid model")
          (is (equal working
                 (getf (th-gen-record id "gen-admin") :model))
              "Working model must be left untouched")))
      (be-delete :models id "gen-admin"))))

(test apply-generated-model-text-replaces-failed-model
  "Rule 2.1: when the prior model is itself a failed attempt
 (;; failed: marker), a new failure replaces it — iteration on
 failures, no accumulation."
  (th-gen-make-user "gen-admin")
  (let ((id (th-gen-make-model-row "gen-admin" "A todo app")))
    (is-true id)
    (unwind-protect
      (progn
        ;; Seed a prior failed attempt
        (be-set-field-value :models id :model
          ";; failed: parse error in model text
'(:old-failure)"
          "gen-admin")
        (let* ((record (th-gen-record id "gen-admin"))
               (prior (getf record :model))
               (result (apply-generated-model-text
                         :models record "gen-admin" :model
                         "A todo app" "'garbage" prior)))
          (is (getf result :error) "Should reject invalid model")
          (let ((model-val (getf (th-gen-record id "gen-admin") :model)))
            (is (search ";; failed: " (or model-val ""))
                "New failed attempt should replace the old one")
            (is-false (search ":old-failure" (or model-val ""))
                      "Old failed attempt must be gone"))))
      (be-delete :models id "gen-admin"))))

(test generate-hook-rejects-no-role
  "Generate hook rejects users without ai-user role."
  (th-make-user "no-role-user" :roles '("models-user"))
  (let ((id (th-gen-make-model-row "no-role-user" "A todo app")))
    (is-true id)
    (unwind-protect
      (let ((result (be-action :models id :generate "no-role-user")))
        (is (equal (getf result :status) "failed"))
        (is (search "ai-user" (or (getf result :message) ""))))
      (be-delete :models id "no-role-user"))))

(test deploy-hook-rejects-no-role
  "FR-7: Deploy hook rejects users without the deployer role, before
model-text validation (blanket deny, no worker spawned)."
  (th-make-user "no-deployer-user" :roles '("models-user"))
  (let ((id (th-gen-make-model-row "no-deployer-user" "A todo app")))
    (is-true id)
    (unwind-protect
      (let ((result (be-action :models id :deploy "no-deployer-user")))
        (is (equal (getf result :status) "failed"))
        (is (search "deployer" (or (getf result :message) "")))
        ;; The role check fires before validation, so even a valid model
        ;; text is denied — the check is not merely first in line.
        (is (search "deployer" (or (getf result :message) ""))))
      (be-delete :models id "no-deployer-user"))))

(test deploy-hook-accepts-role-validates-text
  "FR-7 positive path: a user WITH the deployer role gets past the
role check and fails on empty model text (validation failure, not a
blanket deny) — proving the check is not an unconditional reject."
  (th-make-user "deployer-user" :roles '("models-user" "deployer"))
  (let ((id (th-gen-make-model-row "deployer-user" "A todo app")))
    (is-true id)
    (unwind-protect
      (let ((result (be-action :models id :deploy "deployer-user")))
        (is (equal (getf result :status) "failed"))
        (is (search "empty" (or (getf result :message) "")))
        (is-false (search "deployer role"
                    (or (getf result :message) ""))))
      (be-delete :models id "deployer-user"))))

(test generate-hook-rejects-empty-description
  "Generate hook rejects empty descriptions."
  (th-gen-make-user "gen-admin")
  (let ((id (be-insert :models
              (list :name "empty-desc"
                    :description ""
                    :model "")
              "gen-admin"
              :roles '("models-user"))))
    (is-true id)
    (unwind-protect
      (let ((result (be-action :models id :generate "gen-admin")))
        (is (equal (getf result :status) "failed"))
        (is (search "description" (or (getf result :message) ""))))
      (be-delete :models id "gen-admin"))))

(test generate-hook-async-with-stub
  "Generate hook returns async and worker writes model via stub."
  (th-gen-seed-llm-config)
  (th-gen-make-user "gen-admin")
  (let ((id (th-gen-make-model-row "gen-admin" "A todo app")))
    (is-true id)
    (let ((*generate-model-llm-override*
            (lambda (desc prior)
              (declare (ignore desc prior))
              (list :ok *gen-valid-model*))))
      (let ((result (be-action :models id :generate "gen-admin")))
        (is (getf result :async) "Should return async")
        (let ((status (th-gen-wait id "gen-admin")))
          (is (equal status "complete")
              "Worker should set status to complete")
          (let ((model-val
                  (getf (th-gen-record id "gen-admin") :model)))
            (is (search ":types" (or model-val ""))
                "Model should be written")))))))

(test generate-hook-async-fails-on-invalid-llm-output
  "Generate worker sets failed status when LLM returns garbage."
  (th-gen-seed-llm-config)
  (th-gen-make-user "gen-admin")
  (let ((id (th-gen-make-model-row "gen-admin" "A todo app")))
    (is-true id)
    (let ((*generate-model-llm-override*
            (lambda (desc prior)
              (declare (ignore desc prior))
              (list :ok "this is not a valid model plist"))))
      (be-action :models id :generate "gen-admin")
      (let ((status (th-gen-wait id "gen-admin")))
        (is (search "failed" (or status ""))
            "Status should contain 'failed'")))))

(test be-action-passes-roles
  "be-action threads :roles into the hook (regression for Step 1).
The hook must return synchronously (no llm-config) so no async
worker is spawned."
  (th-gen-delete-llm-config)
  (th-gen-make-user "gen-admin")
  (let ((id (th-gen-make-model-row "gen-admin" "A todo app")))
    (is-true id)
    (unwind-protect
      (let ((result (be-action :models id :generate "gen-admin")))
        (is (or (getf result :async)
                (equal (getf result :status) "failed")))
        (is-false (search "ai-user role"
                    (or (getf result :message) ""))))
      (be-delete :models id "gen-admin"))))

(test generate-hook-persists-data-before-generating
  "Step 3: when :data carries the description/model keys, the hook
be-updates exactly those two fields before generating — browser state
is what gets stored and prompted.  Erase-and-Generate persists \"\" →
blank prior-model gate → fresh generation."
  (th-gen-seed-llm-config)
  (th-gen-make-user "gen-admin")
  (let ((id (th-gen-make-model-row "gen-admin" "A todo app")))
    (is-true id)
    (unwind-protect
      (let* ((seen-prior nil)
             (*generate-model-llm-override*
               (lambda (desc prior)
                 (setf seen-prior prior)
                 (list :ok *gen-valid-model*))))
        (be-action :models id :generate "gen-admin"
          (list :description "A better todo app"
                :model ""))
        (let ((status (th-gen-wait id "gen-admin")))
          (is (equal status "complete"))
          ;; The unsaved :data description was persisted
          (is (equal "A better todo app"
                 (getf (th-gen-record id "gen-admin") :description)))
          ;; Blank :model in :data → prior-model gate omitted it
          (is (or (null seen-prior) (string= seen-prior "")))
          ;; The prompt used the resolved (browser) description
          ;; indirectly: worker succeeded and wrote the model.
          (is (search ":types"
                 (or (getf (th-gen-record id "gen-admin") :model) "")))))
      (be-delete :models id "gen-admin"))))

(test generate-hook-passes-prior-model-to-llm
  "Step 2: a non-empty record :model rides the user message as
advisory prior art (reprogrammatic be-action, no :data — the only
reachable record-only path)."
  (th-gen-seed-llm-config)
  (th-gen-make-user "gen-admin")
  (let ((id (th-gen-make-model-row "gen-admin" "A todo app")))
    (is-true id)
    (unwind-protect
      (let* ((seen-prior nil)
             (*generate-model-llm-override*
               (lambda (desc prior)
                 (setf seen-prior prior)
                 (list :ok *gen-valid-model*))))
        (be-set-field-value :models id :model "'(:name \"seed\")"
          "gen-admin")
        (be-action :models id :generate "gen-admin")
        (th-gen-wait id "gen-admin")
        (is (equal "'(:name \"seed\")" seen-prior)
            "Prior model must reach the LLM call"))
      (be-delete :models id "gen-admin"))))

(test generate-hook-skips-persist-without-data
  "Step 3 fallback: a programmatic be-action with no :data skips the
be-update entirely and resolves both fields from the record."
  (th-gen-seed-llm-config)
  (th-gen-make-user "gen-admin")
  (let ((id (th-gen-make-model-row "gen-admin" "Stored description")))
    (is-true id)
    (unwind-protect
      (let* ((seen-desc nil)
             (*generate-model-llm-override*
               (lambda (desc prior)
                 (declare (ignore prior))
                 (setf seen-desc desc)
                 (list :ok *gen-valid-model*))))
        (be-action :models id :generate "gen-admin")
        (th-gen-wait id "gen-admin")
        (is (equal "Stored description" seen-desc)
            "Record description must be used when :data is nil"))
      (be-delete :models id "gen-admin"))))

(test generate-model-system-prompt-carries-demos
  "The system prompt carries every demo model verbatim: part 2 opens
with the # Examples heading, block markers by path, real demo
content — and no test fixtures (the fixtures live in models/test/
and must never ride the prompt).  Fixture names that also appear
inside model-reference.md prose (m2m, static-select-test) are
excluded from the check for that reason.  NUL-freeness guards the
fixed u:slurp (dc-eclectic): modelbank.lisp carries an em-dash, so
a byte-sized buffer regression would leak trailing NULs here."
  (let ((prompt (generate-model-system-prompt)))
    (is (search "models/todos.lisp" prompt))
    (is (search ":title \"To Do List\"" prompt))
    (is (search "models/modelbank.lisp" prompt))
    (is (search "models/widgets.lisp" prompt))
    (is (search "# Examples" prompt)
      "part 2 must open with the # Examples heading")
    (is-false (search (string (code-char 0)) prompt)
      "the prompt must be NUL-free")
    ;; No fixture FILES ride the prompt: no demo block can contain a
    ;; fixture, and fixture-only names (bi-m2m-test is named only in
    ;; models/test/, never in model-reference.md) are absent.  (The
    ;; literal strings m2m-test / static-select-test appear inside
    ;; model-reference.md prose itself, so they cannot be used here.)
    (is-false (search ";; --- ~/common-lisp/data-ui/models/test/" prompt)
      "test fixtures must not ride the system prompt")
    (is-false (search "bi-m2m-test" prompt)
      "test fixtures must not ride the system prompt")))

(test generate-model-examples-text-shape
  "Part 2 opens with the level-1 # Examples heading, then the
framing prose, then the example blocks — and the joined system
prompt carries the reference before it."
  (let ((examples (generate-model-examples-text)))
    (is (u:starts-with examples "# Examples")
      "part 2 must open with the heading")
    (is (search "complete example models" examples)
      "framing prose must follow the heading")
    (is (> (search "complete example models" examples) 0)
      "prose comes after the heading, not before")
    (is-false (search "~" examples)
      "the prose must carry no format-directive residue")
    (is (search ";; --- " examples)
      "example blocks must follow")))

