(in-package :data-ui)

(def-suite generator-suite
  :description "Generate-model hook tests")

(def-suite generator-pure-suite
  :description "Pure function tests (no model, no DB)"
  :in generator-suite)

(def-suite generator-integration-suite
  :description "Integration tests (need modelbank-test + DB)"
  :in generator-suite)

;;; Reusable valid model text for integration tests.
(defparameter *gen-valid-model*
  (concatenate 'string
    "'(:title \"Gen\" :name \"gen\" :version \"0.1\""
    "  :types (:todos (:table t"
    "    :create :auto :update :auto :delete :auto :display t"
    "    :fields (:name (:type :text :identity t"
    "      :ui (:label \"Name\" :widget :textbox)"
    "      :source (:view :main :column :name :agg :first)"
    "      :column t :not-null t :unique t))"
    "    :list-form (:fields t)"
    "    :update-form (:fields t)"
    "    :add-form (:fields t))))"))

;;; ---------------------------------------------------------------------------
;;; Pure function tests (no model, no DB)
;;; ---------------------------------------------------------------------------

(in-suite generator-pure-suite)

(test strip-leading-comments-basic
  "strip-leading-lisp-comments removes ;; and blank lines."
  (is (equal "'(:types (:foo))"
        (u:trim
          (strip-leading-lisp-comments
            ";; Purpose: test
'(:types (:foo))"))))
  (is (equal "'(:types (:foo))"
        (u:trim
          (strip-leading-lisp-comments
            ";; line 1
;; line 2

'(:types (:foo))"))))
  (is (equal ""
        (strip-leading-lisp-comments
          ";; only comments
;; more comments"))))

(test strip-leading-comments-preserves-inner
  "Comments inside the plist body are preserved."
  (let ((result (strip-leading-lisp-comments
                  "'(:types ;; inner comment
     (:foo))")))
    (is (search ";; inner comment" result))
    (is (search "'(:types" result))))

(test validate-deploy-model-text-accepts-comments
  "validate-deploy-model-text accepts leading ;; headers."
  (let ((result (validate-deploy-model-text
                  (concatenate 'string
                    ";; Purpose: test
;; Author: rose
" *gen-valid-model*))))
    (is (getf result :ok) "Should succeed with leading comments")
    (is-false (getf result :error))))

(test validate-deploy-model-text-rejects-bad-body
  "validate-deploy-model-text still rejects garbage after comments."
  (let ((result (validate-deploy-model-text
                  ";; comment
garbage")))
    (is (getf result :error))))

(test clean-llm-response-strips-fences
  "clean-llm-response strips markdown fences."
  (is (equal "'(:types (:foo))"
        (clean-llm-response
          "```lisp
'(:types (:foo))
```")))
  (is (equal "'(:types (:foo))"
        (clean-llm-response
          "```
'(:types (:foo))
```")))
  (is (equal "'(:types (:foo))"
        (clean-llm-response "'(:types (:foo))")))
  (is (equal "'(:types (:foo))"
        (clean-llm-response
          "Here is the model:
```common-lisp
'(:types (:foo))
```
Hope this helps!"))))

(test generate-model-header-format
  "generate-model-header produces ;; comment lines."
  (let ((header (generate-model-header "a todo app")))
    (is (search ";; Generated by Data UI Model Generator" header))
    (is (search ";; Created:" header))
    (is (search ";; Prompt: a todo app" header))))

(test generate-model-header-truncates-long-prompts
  "generate-model-header truncates prompts over 60 chars."
  (let ((header (generate-model-header
                  (make-string 100 :initial-element #\x))))
    (is (search "..." header))))

;;; ---------------------------------------------------------------------------
;;; Integration tests (need modelbank-test + DB)
;;; ---------------------------------------------------------------------------

(in-suite generator-integration-suite)

(defun th-gen-seed-llm-config ()
  "Insert the llm-config secret as admin, or re-insert if it was
deleted.  Idempotent: deletes any existing llm-config rows first
to avoid duplicates.  Returns NIL."
  (th-gen-delete-llm-config)
  (be-insert :secrets
    (list :name "llm-config"
          :value ":url \"http://fake\" :model \"fake\" :api-key \"fake-key\""
          :description "Test LLM config")
    "admin")
  nil)

(defun th-gen-delete-llm-config ()
  "Delete all llm-config secrets so read-llm-config-missing can run."
  (let* ((result (be-list :secrets "admin" :form :update-form))
         (records (getf result :records)))
    (dolist (record records)
      (when (equal (getf record :name) "llm-config")
        (let ((id (getf record :id)))
          (when id
            (handler-case (be-delete :secrets id "admin")
              (error ())))))))
  nil)

(defun th-gen-make-user (&optional (name "gen-user"))
  "Create a user with ai-user and models-user roles.
Idempotent: skips creation if the user already exists."
  (unless (a:get-id *rbac* "users" name)
    (th-make-user name :roles '("ai-user" "models-user")))
  name)

(defparameter *gen-row-counter* 0)

(defun th-gen-make-model-row (user description)
  "Insert a :models row with a unique name, empty model.
Returns the new record ID."
  (incf *gen-row-counter*)
  (be-insert :models
    (list :name (format nil "gen-test-~d" *gen-row-counter*)
          :description description
          :model "")
    user
    :roles '("models-user")))

(defun th-gen-record (id user)
  "Fetch a :models record by ID."
  (getf (rec id user :type-key :models) :record))

(defun th-gen-status (id user)
  "Fetch the generate-status field for a :models record."
  (getf (th-gen-record id user) :generate-status))

(defun th-gen-wait (id user &optional (timeout 50))
  "Poll until generate-status is no longer running. Returns status."
  (loop for i below timeout
        for status = (th-gen-status id user)
        when (and status (not (equal status "running")))
          do (return status)
        do (sleep 0.1)
        finally (return (th-gen-status id user))))

(test read-llm-config-missing
  "read-llm-config returns error when secret is absent."
  (th-gen-delete-llm-config)
  (let ((result (read-llm-config)))
    (is (getf result :error))))

(test read-llm-config-success
  "read-llm-config parses a valid llm-config secret."
  (th-gen-seed-llm-config)
  (let ((result (read-llm-config)))
    (is (getf result :ok) "Should parse successfully")
    (is (equal "http://fake"
           (getf (getf result :ok) :url)))))

(test admin-secret-value-returns-value
  "admin-secret-value returns the :value for a named secret."
  (th-gen-seed-llm-config)
  (let ((val (admin-secret-value "llm-config")))
    (is (search "fake-key" (or val "")))))

(test apply-generated-model-text-writes-valid
  "apply-generated-model-text writes a valid model with header."
  (th-gen-make-user "gen-admin")
  (let ((id (th-gen-make-model-row "gen-admin" "A todo app")))
    (is-true id)
    (unwind-protect
      (let* ((record (th-gen-record id "gen-admin"))
             (result (apply-generated-model-text
                       :models record "gen-admin" :model
                       "A todo app" *gen-valid-model*)))
        (is (getf result :ok) "Apply should succeed")
        (let ((model-val (getf (th-gen-record id "gen-admin") :model)))
          (is (search ";; Generated by" (or model-val "")))
          (is (search ":types" (or model-val "")))))
      (be-delete :models id "gen-admin"))))

(test apply-generated-model-text-rejects-invalid
  "apply-generated-model-text rejects invalid model text."
  (th-gen-make-user "gen-admin")
  (let ((id (th-gen-make-model-row "gen-admin" "A todo app")))
    (is-true id)
    (unwind-protect
      (let* ((record (th-gen-record id "gen-admin"))
             (result (apply-generated-model-text
                       :models record "gen-admin" :model
                       "A todo app" "'garbage")))
        (is (getf result :error) "Should reject invalid model")
        (let ((model-val (getf (th-gen-record id "gen-admin") :model)))
          (is (or (null model-val) (string= model-val ""))
              "Model field should be untouched")))
      (be-delete :models id "gen-admin"))))

(test generate-hook-rejects-no-role
  "Generate hook rejects users without ai-user role."
  (th-make-user "no-role-user" :roles '("models-user"))
  (let ((id (th-gen-make-model-row "no-role-user" "A todo app")))
    (is-true id)
    (unwind-protect
      (let ((result (be-action :models id :generate "no-role-user")))
        (is (equal (getf result :status) "failed"))
        (is (search "ai-user" (or (getf result :message) ""))))
      (be-delete :models id "no-role-user"))))

(test generate-hook-rejects-empty-description
  "Generate hook rejects empty descriptions."
  (th-gen-make-user "gen-admin")
  (let ((id (be-insert :models
              (list :name "empty-desc"
                    :description ""
                    :model "")
              "gen-admin"
              :roles '("models-user"))))
    (is-true id)
    (unwind-protect
      (let ((result (be-action :models id :generate "gen-admin")))
        (is (equal (getf result :status) "failed"))
        (is (search "description" (or (getf result :message) ""))))
      (be-delete :models id "gen-admin"))))

(test generate-hook-async-with-stub
  "Generate hook returns async and worker writes model via stub."
  (th-gen-seed-llm-config)
  (th-gen-make-user "gen-admin")
  (let ((id (th-gen-make-model-row "gen-admin" "A todo app")))
    (is-true id)
    (let ((*generate-model-llm-override*
            (lambda (desc)
              (declare (ignore desc))
              (list :ok *gen-valid-model*))))
      (let ((result (be-action :models id :generate "gen-admin")))
        (is (getf result :async) "Should return async")
        (let ((status (th-gen-wait id "gen-admin")))
          (is (equal status "complete")
              "Worker should set status to complete")
          (let ((model-val
                  (getf (th-gen-record id "gen-admin") :model)))
            (is (search ":types" (or model-val ""))
                "Model should be written")))))))

(test generate-hook-async-fails-on-invalid-llm-output
  "Generate worker sets failed status when LLM returns garbage."
  (th-gen-seed-llm-config)
  (th-gen-make-user "gen-admin")
  (let ((id (th-gen-make-model-row "gen-admin" "A todo app")))
    (is-true id)
    (let ((*generate-model-llm-override*
            (lambda (desc)
              (declare (ignore desc))
              (list :ok "this is not a valid model plist"))))
      (be-action :models id :generate "gen-admin")
      (let ((status (th-gen-wait id "gen-admin")))
        (is (search "failed" (or status ""))
            "Status should contain 'failed'")))))

(test be-action-passes-roles
  "be-action threads :roles into the hook (regression for Step 1).
The hook must return synchronously (no llm-config) so no async
worker is spawned."
  (th-gen-delete-llm-config)
  (th-gen-make-user "gen-admin")
  (let ((id (th-gen-make-model-row "gen-admin" "A todo app")))
    (is-true id)
    (unwind-protect
      (let ((result (be-action :models id :generate "gen-admin")))
        (is (or (getf result :async)
                (equal (getf result :status) "failed")))
        (is-false (search "ai-user role"
                    (or (getf result :message) ""))))
      (be-delete :models id "gen-admin"))))
