#!/bin/bash

SCRIPT_NAME=$(basename $0)
ACTION="$1"

# Environment
if [ $ACTION = "repl" ]; then
    export DB_CONTAINER="pg-data-ui-repl"
    export DB_PORT="5438"
    export LOG_FILE="tests/repl.log"
    export SWANK_PORT="4010"
    export RUN_TESTS="false"
    export REPL_ENABLED="true"
else
    export DB_CONTAINER="pg-data-ui-test"
    export DB_PORT="5437"
    export LOG_FILE="tests/test.log"
    export RUN_TESTS="true"
    export REPL_ENABLED="false"
fi

export ADMIN_PASSWORD="admin-password-1"
export DB_CONTAINER="pg-data-ui-repl"
export DB_DOCKER_COMPOSE="tests/docker-compose-${DB_CONTAINER}.yaml"
export DB_HOST="127.0.0.1"
export DB_INIT_TEMPLATE="tests/init-template.sql"
export DB_INIT_SQL="tests/init.sql"
export DB_NAME="data_ui"
export DB_PASSWORD="data-ui-password"
export DB_USER="data_ui"
export DOCUMENT_ROOT="tests/shared-files"
export PGPASSWORD="$DB_PASSWORD"
export TEST_FILE="tests/data-ui-tests.lisp"

sed "s/:database_name:/$DB_NAME/" $DB_INIT_TEMPLATE > $DB_INIT_SQL

function usage {
    echo "Usage:"
    echo "    $SCRIPT_NAME {command}"
    echo
    echo "Commands:"
    echo "repl     Starts a Common Lisp REPL (using Roswell) that loads the"
    echo "         test file at $TEST_FILE, but doesn't run the tests. You"
    echo "         can connect to the REPL with the a client like Slime at"
    echo "         the reported Swank port."
    echo "tests    Runs all the tests and reports success or failure."
    echo "stop     Stops the database container and removes it. This is"
    echo "         normally not necessary."
    echo "debug    Runs the tests, printing all output from postgres and"
    echo "         docker compose."
    echo "help     Displays this help text."
}

function start_postgres_quietly {
    echo
    echo "Starting PosgreSQL"
    docker-compose -f "$DB_DOCKER_COMPOSE" up -d &>/dev/null
    until docker-compose -f "$DB_DOCKER_COMPOSE" exec -it "$DB_CONTAINER" \
                         pg_isready -U postgres &>/dev/null; do
        echo "Waiting for postgres..."
        sleep 1
    done
    echo "PostgreSQL is up on port ${DB_PORT}"
    sleep 2
}

function start_postgres {
    echo
    echo "Starting PosgreSQL"
    docker-compose -f "$DB_DOCKER_COMPOSE" up -d
    until docker-compose -f "$DB_DOCKER_COMPOSE" exec -it "$DB_CONTAINER" \
                         pg_isready -U postgres; do
        echo "Waiting for postgres..."
        sleep 1
    done
    echo "PostgreSQL is up on port ${DB_PORT}"
    sleep 2
}

function initialize_database_quietly {
    echo
    echo -n "Initializing database... "
    psql -h $DB_HOST -p $DB_PORT -d $DB_NAME -U $DB_USER \
         -f "$DB_INIT_SQL" >&/dev/null
    echo "Done."
}

function initialize_database {
    echo
    echo "Initializing database"
    psql -h $DB_HOST -p $DB_PORT -d $DB_NAME -U $DB_USER \
         -f "$DB_INIT_SQL"
}

function start_repl {
    echo
    echo "Starting REPL"
    ros run -- --load "$TEST_FILE"
}

function run_tests {
    echo
    echo "Running tests"
    ros run -- --disable-debugger --load "$TEST_FILE" --quit
    REPORT=$( [[ $? -eq 0 ]] && echo "PASS" || echo "FAIL" )
}

function stop_database {
    echo "Stopping and removing database container"
    docker-compose -f "$DB_DOCKER_COMPOSE" down
}

function stop_database_quietly {
    echo "Stopping and removing database container"
    docker-compose -f "$DB_DOCKER_COMPOSE" down &>/dev/null
}

case "$ACTION" in
    repl)
        start_postgres_quietly
        initialize_database_quietly
        start_repl
        stop_database_quietly
        ;;
    tests)
        start_postgres_quietly
        initialize_database_quietly
        run_tests
        stop_database_quietly
        ;;
    debug)
        start_postgres
        initialize_database
        run_tests
        stop_database
        ;;
    stop)
        stop_database
        ;;
    help)
        usage
        exit 0
        ;;
    *)
        if [[ -z "$ACTION" ]]; then
            echo "Unknown command $ACTION"
        else
            echo "Missing command"
        fi
        usage
        exit 1
        ;;
esac
