# Generated by scripts/data-ui deploy -- instance {{NAME}} ({{TAG}})
apiVersion: v1
kind: Namespace
metadata:
  name: {{NAMESPACE}}
  labels:
    app.kubernetes.io/managed-by: data-ui-deploy
    data-ui/instance: {{NAME}}
