# Generated by scripts/run.sh deploy -- instance {{NAME}} ({{TAG}})
apiVersion: v1
kind: Secret
metadata:
  name: dataui-{{NAME}}-secrets
  namespace: {{NAMESPACE}}
  labels:
    data-ui/instance: {{NAME}}
type: Opaque
stringData:
  db-password: "{{DB_PASSWORD}}"
  admin-password: "{{ADMIN_PASSWORD}}"
  jwt-secret: "{{JWT_SECRET}}"
