# Generated by scripts/run.sh deploy -- instance {{NAME}} ({{TAG}})
#
# hostPath volumes live inside the k3d node container. They survive pod
# restarts and image rollouts, but not deletion of the k3d cluster.
# NOTE: multiple replicas would require ReadWriteMany (e.g. EFS) on a
# real cluster later.
apiVersion: v1
kind: PersistentVolume
metadata:
  name: dataui-{{NAME}}-{{ENV}}-db-pv
  labels:
    data-ui/instance: {{NAME}}
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /data/dataui/{{NAME}}-{{ENV}}/db
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: dataui-{{NAME}}-{{ENV}}-files-pv
  labels:
    data-ui/instance: {{NAME}}
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /data/dataui/{{NAME}}-{{ENV}}/files
    type: DirectoryOrCreate
