# Generated by scripts/data-ui deploy -- instance {{NAME}} ({{TAG}})
#
# hostPath volumes live on the host SSD at /data/k8s/data-ui/, bound
# into the k3d node at the same path (-v /data/k8s:/data/k8s). They
# survive pod restarts, image rollouts, and k3d cluster recreation.
# NOTE: multiple replicas would require ReadWriteMany (e.g. EFS) on a
# real cluster later.
apiVersion: v1
kind: PersistentVolume
metadata:
  name: dataui-{{NAME}}-{{ENV}}-db-pv
  labels:
    data-ui/instance: {{NAME}}
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /data/k8s/data-ui/{{NAME}}-{{ENV}}/db
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: dataui-{{NAME}}-{{ENV}}-files-pv
  labels:
    data-ui/instance: {{NAME}}
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /data/k8s/data-ui/{{NAME}}-{{ENV}}/files
    type: DirectoryOrCreate
