# Generated by scripts/run.sh deploy -- instance {{NAME}} ({{TAG}})
#
# PVC names are stable across versions so a new image rollout reuses the
# existing volumes.
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dataui-{{NAME}}-db
  namespace: {{NAMESPACE}}
  labels:
    data-ui/instance: {{NAME}}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  volumeName: dataui-{{NAME}}-{{ENV}}-db-pv
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dataui-{{NAME}}-files
  namespace: {{NAMESPACE}}
  labels:
    data-ui/instance: {{NAME}}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  volumeName: dataui-{{NAME}}-{{ENV}}-files-pv
  resources:
    requests:
      storage: 5Gi
