# Generated by scripts/run.sh deploy -- instance {{NAME}} ({{TAG}})
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dataui-{{NAME}}-postgres
  namespace: {{NAMESPACE}}
  labels:
    app: dataui-{{NAME}}-postgres
    data-ui/instance: {{NAME}}
spec:
  replicas: 1
  # Recreate so the old pod releases the volume before the new pod mounts it.
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: dataui-{{NAME}}-postgres
  template:
    metadata:
      labels:
        app: dataui-{{NAME}}-postgres
        data-ui/instance: {{NAME}}
    spec:
      containers:
        - name: postgres
          image: postgres:16
          imagePullPolicy: IfNotPresent
          env:
            - name: POSTGRES_USER
              value: "dataui"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: dataui-{{NAME}}-secrets
                  key: db-password
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          ports:
            - containerPort: 5432
              name: postgres
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "dataui"]
            initialDelaySeconds: 5
            periodSeconds: 5
          volumeMounts:
            - name: db-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: db-data
          persistentVolumeClaim:
            claimName: dataui-{{NAME}}-db
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: {{NAMESPACE}}
  labels:
    data-ui/instance: {{NAME}}
spec:
  type: ClusterIP
  selector:
    app: dataui-{{NAME}}-postgres
  ports:
    - port: 5432
      targetPort: 5432
