# Generated by scripts/run.sh deploy -- instance {{NAME}} ({{TAG}})
#
# Lines marked #@repl are kept only when the model's :repl key is true.
# The Swank port is never exposed through a Service; reach it with
#   kubectl -n {{NAMESPACE}} port-forward deploy/dataui-{{NAME}} 4005:4005
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dataui-{{NAME}}
  namespace: {{NAMESPACE}}
  labels:
    app: dataui-{{NAME}}
    data-ui/instance: {{NAME}}
    data-ui/version: "{{TAG}}"
spec:
  replicas: 1
  # Recreate: the files PVC is ReadWriteOnce.
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: dataui-{{NAME}}
  template:
    metadata:
      labels:
        app: dataui-{{NAME}}
        data-ui/instance: {{NAME}}
        data-ui/version: "{{TAG}}"
    spec:
      initContainers:
        - name: init-db
          image: postgres:16
          imagePullPolicy: IfNotPresent
          env:
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: dataui-{{NAME}}-secrets
                  key: db-password
          command:
            - /bin/sh
            - -c
            - |
              until pg_isready -h postgres -U dataui; do
                echo "waiting for postgres..."
                sleep 2
              done
              if psql -h postgres -U dataui -d dataui -tAc \
                   "select 1 from information_schema.tables where table_name='users'" \
                   | grep -q 1; then
                echo "Schema already initialized; skipping init SQL."
              else
                psql -h postgres -U dataui -d dataui -v ON_ERROR_STOP=1 \
                     -f /init/init.sql
              fi
          volumeMounts:
            - name: init-sql
              mountPath: /init
      containers:
        - name: data-ui
          image: "{{IMAGE}}"
          imagePullPolicy: IfNotPresent
          env:
            - name: HTTP_HOST
              value: "0.0.0.0"
            - name: HTTP_PORT
              value: "8080"
            - name: DB_HOST
              value: "postgres"
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: "dataui"
            - name: DB_USER
              value: "dataui"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: dataui-{{NAME}}-secrets
                  key: db-password
            - name: ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: dataui-{{NAME}}-secrets
                  key: admin-password
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: dataui-{{NAME}}-secrets
                  key: jwt-secret
            - name: DOCUMENT_ROOT
              value: "/app/shared-files/"
            - name: FS_TEMP_DIRECTORY
              value: "/app/temp-files/"
            - name: WEB_DIRECTORY
              value: "/app/web"
            - name: DATAUI_VERSION
              value: "{{TAG}}"
            - name: DATAUI_ENVIRONMENT
              value: "{{ENV}}"
            - name: SWANK_PORT #@repl
              value: "4005" #@repl
          ports:
            - containerPort: 8080
              name: http
            - containerPort: 4005 #@repl
              name: swank #@repl
          # First boot initializes the database; give it up to 5 minutes
          # before liveness applies. A mid-init kill must never happen:
          # initialization is not idempotent, so partial state wedges
          # the instance.
          startupProbe:
            httpGet:
              path: /health
              port: 8080
            periodSeconds: 5
            failureThreshold: 60
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            periodSeconds: 15
          volumeMounts:
            - name: files
              mountPath: /app/shared-files
            - name: temp-files
              mountPath: /app/temp-files
      volumes:
        - name: files
          persistentVolumeClaim:
            claimName: dataui-{{NAME}}-files
        - name: temp-files
          emptyDir: {}
        - name: init-sql
          configMap:
            name: dataui-{{NAME}}-init-sql
---
apiVersion: v1
kind: Service
metadata:
  name: dataui-{{NAME}}
  namespace: {{NAMESPACE}}
  labels:
    data-ui/instance: {{NAME}}
spec:
  type: NodePort
  selector:
    app: dataui-{{NAME}}
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: {{NODE_PORT}}
