# Generated by scripts/run.sh deploy -- Data UI instance {{NAME}} ({{TAG}})
# Routes {{DOMAIN}} -> k3d node {{NODE_IP}}, NodePort {{NODE_PORT}}.
# Installed to /etc/haproxy/conf.d/dataui-{{NAME}}.cfg; the matching map
# entry lives in /etc/haproxy/data-ui.map.
backend dataui-{{NAME}}
    mode http
    option forwardfor
    option httpchk GET /health
    server dataui-{{NAME}} {{NODE_IP}}:{{NODE_PORT}} check inter 2000 rise 2 fall 3
