# Generated by scripts/data-ui deploy -- Data UI instance {{NAME}} ({{TAG}})
# Routes {{DOMAIN}} -> {{NODE_TARGET}}: the k3d-published loopback hop
# (127.0.0.1:<nodePort+1000>) when it answers at render time, else the
# node's bridge IP {{NODE_IP}} with NodePort {{NODE_PORT}}.
# Installed to /etc/haproxy/conf.d/dataui-{{NAME}}.cfg; the matching map
# entry lives in /etc/haproxy/data-ui.map.
backend dataui-{{NAME}}
    mode http
    option forwardfor
    option httpchk GET /health
    server dataui-{{NAME}} {{NODE_TARGET}} check inter 2000 rise 2 fall 3
