;; Generated by Data UI Model Generator
;; Created: 2026-07-28T00:15:34
;; Prompt: This application tracks gifts that the user wishes to rec...
'(:title "Gift List"
  :name "gift-list"
  :version "0.1"
  :domain "gifts.demo.data-ui.com"
  :repl nil
  :landing-page :gifts
  :types
  (:gifts
    (:table t
      :create :auto :update :auto :delete :auto :display t
      :type-roles ("gift-users")
      :views (:main (:tables (:gifts :gift-viewers :users))
               :scoped (:tables (:gifts) :scope :user))
      :fields
      (:name
        (:type :text :identity t
          :ui (:label "Gift" :widget :textbox)
          :validations (:required)
          :source (:view :main :column :name :agg :first)
          :column t :not-null t)
       :url
        (:type :text
          :ui (:label "Link" :widget :textbox)
          :source (:view :main :column :url :agg :first)
          :column t)
       :received
        (:type :boolean :default :false
          :ui (:label "Received" :widget :checkbox)
          :source (:view :main :column :received :agg :first)
          :column t :not-null t)
       :received-event
        (:type :text
          :ui (:label "Received For" :widget :textbox)
          :source (:view :main :column :received-event :agg :first)
          :column t)
       :viewers
        (:type :list
          :ui (:label "Restrict Viewers" :widget :checkbox-list)
          :validations (:join-items-exist)
          :source (:view :main :table :users :column :name :agg :list)
          :source-all (:view :main :table :users :column :name :agg :list)
          :join-table :gift-viewers))
      :list-form (:fields t)
      :update-form (:fields t)
      :add-form (:fields t))

   :gift-viewers
    (:table t :is-joiner t :internal t
      :fields
      (:reference (:target :gifts)
        :reference (:target :users)))))
