;; Generated by Data UI Model Generator
;; Created: 2026-07-28T18:52:39
;; Prompt: This app allows a user to track the gifts he would like t...
'(:title "Gift Tracker"
  :name "gift-tracker"
  :version "0.1"
  :domain "gift-tracker.demo.data-ui.com"
  :domain-stg "gift-tracker-stg.demo.data-ui.com"
  :repl t
  :landing-page :gifts
  :types
  (:gifts
    (:table t
      :create :auto :update :auto :delete :auto :display t
      :type-roles ("gift-viewers")
      :views (:main (:tables (:gifts :users)))
      :fields
      (:name
        (:type :text :identity t
          :ui (:label "Gift" :widget :textbox)
          :validations (:required)
          :source (:view :main :column :name :agg :first)
          :column t :not-null t)
       :url
        (:type :text
          :ui (:label "URL" :widget :textbox)
          :source (:view :main :column :url :agg :first)
          :column t)
       :received
        (:type :boolean :default :false
          :ui (:label "Received" :widget :checkbox)
          :source (:view :main :column :received :agg :first)
          :column t :not-null t)
       :event
        (:type :text
          :ui (:label "Event Received" :widget :textbox)
          :source (:view :main :column :event :agg :first)
          :column t)
       :user
        (:type :text
          :autofill :user
          :force-sql-name "gift_user"
          :ui (:label "Owner" :widget :textbox :read-only t)
          :target :users
          :source (:view :main :table :users :column :name :agg :first)
          :column t :not-null t))
      :list-form (:fields t)
      :update-form (:fields t)
      :add-form (:fields (:name :url :received :event)))))
