'(:TITLE "Gift List" :NAME "gift-list" :VERSION "0.1" :DOMAIN
  "gifts.demo.data-ui.com" :REPL NIL :LANDING-PAGE :GIFTS :TYPES
  (:GIFTS
   (:TABLE T :CREATE :AUTO :UPDATE :AUTO :DELETE :AUTO :DISPLAY T :TYPE-ROLES
    ("gift-users") :VIEWS
    (:MAIN (:TABLES (:GIFTS :GIFT-VIEWERS :USERS)) :SCOPED
     (:TABLES (:GIFTS) :SCOPE :USER))
    :FIELDS
    (:NAME
     (:TYPE :TEXT :IDENTITY T :UI (:LABEL "Gift" :WIDGET :TEXTBOX) :VALIDATIONS
      (:REQUIRED) :SOURCE (:VIEW :MAIN :COLUMN :NAME :AGG :FIRST) :COLUMN T
      :NOT-NULL T)
     :URL
     (:TYPE :TEXT :UI (:LABEL "Link" :WIDGET :TEXTBOX) :SOURCE
      (:VIEW :MAIN :COLUMN :URL :AGG :FIRST) :COLUMN T)
     :RECEIVED
     (:TYPE :BOOLEAN :DEFAULT :FALSE :UI (:LABEL "Received" :WIDGET :CHECKBOX)
      :SOURCE (:VIEW :MAIN :COLUMN :RECEIVED :AGG :FIRST) :COLUMN T :NOT-NULL
      T)
     :RECEIVED-EVENT
     (:TYPE :TEXT :UI (:LABEL "Received For" :WIDGET :TEXTBOX) :SOURCE
      (:VIEW :MAIN :COLUMN :RECEIVED-EVENT :AGG :FIRST) :COLUMN T)
     :VIEWERS
     (:TYPE :LIST :UI (:LABEL "Restrict Viewers" :WIDGET :CHECKBOX-LIST)
      :VALIDATIONS (:JOIN-ITEMS-EXIST) :SOURCE
      (:VIEW :MAIN :TABLE :USERS :COLUMN :NAME :AGG :LIST) :SOURCE-ALL
      (:VIEW :MAIN :TABLE :USERS :COLUMN :NAME :AGG :LIST) :JOIN-TABLE
      :GIFT-VIEWERS))
    :LIST-FORM (:FIELDS T) :UPDATE-FORM (:FIELDS T) :ADD-FORM (:FIELDS T))
   :GIFT-VIEWERS
   (:TABLE T :IS-JOINER T :INTERNAL T :FIELDS
    (:REFERENCE (:TARGET :GIFTS) :REFERENCE (:TARGET :USERS)))))