(:TITLE "Model Bank" :NAME "modelbank" :VERSION "0.1" :DOMAIN
 "modelbank.demo.data-ui.com" :REPL T :LANDING-PAGE :MODELS :TYPES
 (:DIRECTORIES
  (:TABLE T :CREATE :AUTO :UPDATE :AUTO :DELETE :AUTO :DISPLAY T :TREE T
   :IS-LEAF NIL :PARENT-TYPE :DIRECTORIES :FS-BACKED T :TYPE-ROLES
   ("directories-user") :VIEWS (:MAIN (:TABLES (:DIRECTORIES))) :FIELDS
   (:NAME
    (:TYPE :TEXT :IDENTITY T :PATH T :UI (:LABEL "Directory" :INPUT-TYPE :LINE)
     :VALIDATIONS (:REQUIRED) :SOURCE (:VIEW :MAIN :COLUMN :NAME :AGG :FIRST)
     :COLUMN T :NOT-NULL T :UNIQUE T))
   :LIST-FORM (:FIELDS T) :UPDATE-FORM (:FIELDS T) :ADD-FORM (:FIELDS T))
  :MODELS
  (:TABLE T :CREATE :AUTO :UPDATE :AUTO :DELETE :AUTO :DISPLAY T :TYPE-ROLES
   ("models-user") :VIEWS (:MAIN (:TABLES (:MODELS :IMAGES :RATINGS))) :FIELDS
   (:NAME
    (:TYPE :TEXT :IDENTITY T :UI (:LABEL "Model Name" :INPUT-TYPE :LINE)
     :VALIDATIONS (:REQUIRED) :SOURCE (:VIEW :MAIN :COLUMN :NAME :AGG :FIRST)
     :COLUMN T :NOT-NULL T :UNIQUE T)
    :DESCRIPTION
    (:TYPE :TEXT :UI (:LABEL "Model Description" :INPUT-TYPE :TEXTBOX) :SOURCE
     (:VIEW :MAIN :COLUMN :DESCRIPTION :AGG :FIRST) :COLUMN T :NOT-NULL NIL
     :UNIQUE NIL)
    :MODEL
    (:TYPE :TEXT :UI
     (:LABEL "Model Code" :INPUT-TYPE :TEXTBOX :RENDER-AS :CODE) :SOURCE
     (:VIEW :MAIN :COLUMN :MODEL :AGG :FIRST) :COLUMN T :NOT-NULL T :UNIQUE
     NIL)
    :IMAGES
    (:TYPE :LIST :UI
     (:LABEL "Images" :INPUT-TYPE :READ-ONLY :RENDER-AS :IMAGE-LIST) :SOURCE
     (:VIEW :MAIN :TABLE :IMAGES :COLUMN :NAME :AGG :DISTINCT))
    :RATING
    (:TYPE :INTEGER :UI
     (:LABEL "My Rating" :INPUT-TYPE :LINE :RENDER-AS :STARS) :VALIDATIONS
     ((:IN-RANGE :MIN 1 :MAX 5)) :SOURCE
     (:VIEW :MAIN :TABLE :RATINGS :COLUMN :RATING :SCOPE :USER :AGG :FIRST)
     :WRITE-TO (:TABLE :RATINGS :MODEL :THIS :USER :USER :RATING :VALUE))
    :AVERAGE-RATING
    (:TYPE :REAL :UI
     (:LABEL "Rating" :INPUT-TYPE :READ-ONLY :RENDER-AS :STARS :PRECISION 1)
     :SOURCE (:VIEW :MAIN :TABLE :RATINGS :COLUMN :RATING :AGG :AVG))
    :DEPLOY
    (:TYPE :BUTTON :UI (:LABEL "Deploy Model" :INPUT-TYPE :BUTTON) :ACTION
     (:DEPLOY-MODEL :FIELD :MODEL)))
   :LIST-FORM (:FIELDS (:NAME :DESCRIPTION :MODEL :IMAGES :AVERAGE-RATING))
   :UPDATE-FORM (:FIELDS T) :ADD-FORM (:FIELDS T))
  :IMAGES
  (:TABLE T :CREATE :AUTO :UPDATE :AUTO :DELETE :AUTO :DISPLAY T :TREE T
   :IS-LEAF T :PARENT-TYPE :DIRECTORIES :FS-BACKED T :TYPE-ROLES
   ("images-user") :VIEWS
   (:MAIN (:TABLES (:IMAGES :USERS :MODELS) :SCOPE :USER) :USERS
    (:TABLES (:USERS) :SCOPE :USER) :MODELS (:TABLES (:MODELS) :SCOPE :USER))
   :FIELDS
   (:NAME
    (:TYPE :TEXT :IDENTITY T :PATH T :UI
     (:LABEL "File" :INPUT-TYPE :LINE :RENDER-AS :IMAGE) :VALIDATIONS
     (:REQUIRED) :SOURCE (:VIEW :MAIN :COLUMN :NAME :AGG :FIRST) :COLUMN T
     :NOT-NULL T :UNIQUE T)
    :FILE
    (:TYPE :FILE :UI (:LABEL "Select File" :INPUT-TYPE :FILE) :VALIDATIONS
     (:REQUIRED))
    :USER
    (:TYPE :TEXT :AUTOFILL :USER :FORCE-SQL-NAME "image_user" :UI
     (:LABEL "Owner" :INPUT-TYPE :READ-ONLY) :TARGET :USERS :SOURCE
     (:VIEW :MAIN :TABLE :USERS :COLUMN :NAME :AGG :FIRST) :SOURCE-ALL
     (:VIEW :USERS :TABLE :USERS :COLUMN :NAME :AGG :LIST) :COLUMN T :NOT-NULL
     T)
    :MODEL
    (:TYPE :TEXT :FORCE-SQL-NAME "image_model" :UI
     (:LABEL "Model" :INPUT-TYPE :SELECT) :TARGET :MODELS :SOURCE
     (:VIEW :MAIN :TABLE :MODELS :COLUMN :NAME :AGG :FIRST) :SOURCE-ALL
     (:VIEW :MODELS :TABLE :MODELS :COLUMN :NAME :AGG :LIST) :COLUMN T
     :NOT-NULL T))
   :LIST-FORM (:FIELDS T) :UPDATE-FORM (:FIELDS T) :ADD-FORM (:FIELDS T))
  :RATINGS
  (:TABLE T :CREATE :AUTO :UPDATE :AUTO :DELETE :AUTO :DISPLAY T :TYPE-ROLES
   ("ratings-user") :VIEWS
   (:MAIN (:TABLES (:RATINGS :MODELS :USERS) :SCOPE :USER) :MODELS
    (:TABLES (:MODELS)) :USERS (:TABLES (:USERS) :SCOPE :USER))
   :FIELDS
   (:MODEL
    (:TYPE :TEXT :IDENTITY T :FORCE-SQL-NAME "rating_model" :UI
     (:LABEL "Model" :INPUT-TYPE :SELECT) :TARGET :MODELS :SOURCE
     (:VIEW :MAIN :TABLE :MODELS :COLUMN :NAME :AGG :FIRST) :SOURCE-ALL
     (:VIEW :MODELS :TABLE :MODELS :COLUMN :NAME :AGG :LIST) :COLUMN T
     :NOT-NULL T)
    :USER
    (:TYPE :TEXT :IDENTITY T :AUTOFILL :USER :FORCE-SQL-NAME "rating_user" :UI
     (:LABEL "User" :INPUT-TYPE :READ-ONLY) :TARGET :USERS :SOURCE
     (:VIEW :MAIN :TABLE :USERS :COLUMN :NAME :AGG :FIRST) :SOURCE-ALL
     (:VIEW :USERS :TABLE :USERS :COLUMN :NAME :AGG :LIST) :COLUMN T :NOT-NULL
     T)
    :RATING
    (:TYPE :INTEGER :UI (:LABEL "Rating" :INPUT-TYPE :LINE :RENDER-AS :STARS)
     :VALIDATIONS ((:IN-RANGE :MIN 1 :MAX 5)) :SOURCE
     (:VIEW :MAIN :TABLE :RATINGS :COLUMN :RATING :AGG :FIRST) :COLUMN T))
   :LIST-FORM (:FIELDS T) :UPDATE-FORM (:FIELDS T) :ADD-FORM (:FIELDS T))))