'(:TITLE "Parts Tracker" :NAME "parts" :VERSION "0.1" :DOMAIN
  "parts.demo.data-ui.com" :REPL T :TYPES
  (:DIRECTORIES
   (:TABLE T :CREATE :AUTO :UPDATE :AUTO :DELETE :AUTO :DISPLAY T :TREE T
    :IS-LEAF NIL :PARENT-TYPE :DIRECTORIES :FS-BACKED T :TYPE-ROLES ("parts")
    :VIEWS (:MAIN (:TABLES (:DIRECTORIES))) :FIELDS
    (:NAME
     (:TYPE :TEXT :IDENTITY T :PATH T :UI
      (:LABEL "Directory" :INPUT-TYPE :LINE) :VALIDATIONS (:REQUIRED) :SOURCE
      (:VIEW :MAIN :COLUMN :NAME :AGG :FIRST) :COLUMN T :NOT-NULL T :UNIQUE T)
     :BOGUS
     (:TYPE :TEXT :DEFAULT "" :UI (:LABEL "Bogus" :INPUT-TYPE :LINE) :SOURCE
      (:VIEW :MAIN :COLUMN :NAME :AGG :FIRST) :COLUMN T))
    :LIST-FORM (:FIELDS T) :UPDATE-FORM (:FIELDS T) :ADD-FORM (:FIELDS T))
   :FILES
   (:TABLE T :CREATE :AUTO :UPDATE :AUTO :DELETE :AUTO :DISPLAY T :TREE T
    :IS-LEAF T :PARENT-TYPE :DIRECTORIES :FS-BACKED T :TYPE-ROLES ("parts")
    :VIEWS (:MAIN (:TABLES (:FILES))) :FIELDS
    (:NAME
     (:TYPE :TEXT :IDENTITY T :PATH T :UI (:LABEL "File" :INPUT-TYPE :LINE)
      :VALIDATIONS (:REQUIRED) :SOURCE (:VIEW :MAIN :COLUMN :NAME :AGG :FIRST)
      :COLUMN T :NOT-NULL T :UNIQUE T)
     :FILE
     (:TYPE :FILE :UI (:LABEL "Select File" :INPUT-TYPE :FILE) :VALIDATIONS
      (:REQUIRED)))
    :LIST-FORM (:FIELDS T) :UPDATE-FORM (:FIELDS T) :ADD-FORM (:FIELDS T))
   :PARTS
   (:TABLE T :CREATE :AUTO :UPDATE :AUTO :DELETE :AUTO :DISPLAY T :TYPE-ROLES
    ("parts") :VIEWS
    (:MAIN (:TABLES (:PARTS :PART-FILES :FILES)) :FILES (:TABLES (:FILES)))
    :FIELDS
    (:NAME
     (:TYPE :TEXT :IDENTITY T :UI (:LABEL "Part Number" :INPUT-TYPE :LINE)
      :VALIDATIONS (:REQUIRED) :SOURCE (:VIEW :MAIN :COLUMN :NAME :AGG :FIRST)
      :COLUMN T :NOT-NULL T :UNIQUE T)
     :DESCRIPTION
     (:TYPE :TEXT :UI (:LABEL "Part Description" :INPUT-TYPE :TEXT) :SOURCE
      (:VIEW :MAIN :COLUMN :DESCRIPTION :AGG :FIRST) :COLUMN T :NOT-NULL NIL
      :UNIQUE NIL)
     :FILES
     (:TYPE :LIST :UI (:LABEL "Images" :INPUT-TYPE :CHECKBOX-LIST) :VALIDATIONS
      (:JOIN-ITEMS-EXIST) :SOURCE
      (:VIEW :MAIN :TABLE :FILES :COLUMN :NAME :AGG :LIST) :SOURCE-ALL
      (:VIEW :FILES :TABLE :FILES :COLUMN :NAME :AGG :LIST) :JOIN-TABLE
      :PART-FILES))
    :LIST-FORM (:FIELDS T) :UPDATE-FORM (:FIELDS T) :ADD-FORM (:FIELDS T))
   :PART-FILES
   (:TABLE T :IS-JOINER T :INTERNAL T :FIELDS
    (:REFERENCE (:TARGET :PARTS) :REFERENCE (:TARGET :FILES)))))