'(:TITLE "To Do List" :NAME "todos" :VERSION "0.1" :DOMAIN
  "todo.demo.data-ui.com" :REPL T :LANDING-PAGE :TODOS :TYPES
  (:TODOS
   (:TABLE T :CREATE :AUTO :UPDATE :AUTO :DELETE :AUTO :DISPLAY T :TYPE-ROLES
    ("todo-users") :VIEWS
    (:MAIN (:TABLES (:TODOS :TODO-TAGS :TAGS)) :TAGS (:TABLES (:TAGS))) :FIELDS
    (:NAME
     (:TYPE :TEXT :IDENTITY T :UI (:LABEL "To Do" :INPUT-TYPE :LINE)
      :VALIDATIONS (:REQUIRED (:MAX-LENGTH :MAX 19)) :SOURCE
      (:VIEW :MAIN :COLUMN :NAME :AGG :FIRST) :COLUMN T :NOT-NULL T :UNIQUE T)
     :POINTS
     (:TYPE :INTEGER :DEFAULT 0 :UI (:LABEL "Points" :INPUT-TYPE :LINE)
      :VALIDATIONS (:REQUIRED) :SOURCE
      (:VIEW :MAIN :COLUMN :POINTS :AGG :FIRST) :COLUMN T :NOT-NULL T)
     :DONE
     (:TYPE :BOOLEAN :DEFAULT :FALSE :UI (:LABEL "Done" :INPUT-TYPE :CHECK-BOX)
      :SOURCE (:VIEW :MAIN :COLUMN :DONE :AGG :FIRST) :COLUMN T :NOT-NULL T)
     :TAGS
     (:TYPE :LIST :UI (:LABEL "Tags" :INPUT-TYPE :CHECKBOX-LIST) :VALIDATIONS
      (:JOIN-ITEMS-EXIST) :SOURCE
      (:VIEW :MAIN :TABLE :TAGS :COLUMN :NAME :AGG :LIST) :SOURCE-ALL
      (:VIEW :TAGS :TABLE :TAGS :COLUMN :NAME :AGG :LIST) :JOIN-TABLE
      :TODO-TAGS))
    :LIST-FORM (:FIELDS T) :UPDATE-FORM (:FIELDS T) :ADD-FORM (:FIELDS T))
   :TAGS
   (:TABLE T :CREATE :AUTO :UPDATE :AUTO :DELETE :AUTO :DISPLAY T :TYPE-ROLES
    ("todo-users") :FIELDS
    (:NAME
     (:TYPE :TEXT :IDENTITY T :UI (:LABEL "Tag" :INPUT-TYPE :LINE) :VALIDATIONS
      (:REQUIRED) :SOURCE (:VIEW :MAIN :TABLE :TAGS :COLUMN :NAME :AGG :FIRST)
      :COLUMN T :NOT-NULL T :UNIQUE T))
    :LIST-FORM (:FIELDS T) :UPDATE-FORM (:FIELDS T) :ADD-FORM (:FIELDS T))
   :TODO-TAGS
   (:TABLE T :IS-JOINER T :INTERNAL T :FIELDS
    (:REFERENCE (:TARGET :TODOS) :REFERENCE (:TARGET :TAGS)))))